import { z } from 'zod';

export const ProductVariantSchema = z.object({
  size: z.enum(['S', 'M', 'L', 'XL', 'XXL']),
  color: z.string().optional().nullable(), // Allow null or undefined
  stock: z.number().int().nonnegative().default(0),
});

export const ProductSchema = z.object({
  id: z.string().optional(), // Optional because it might not exist before creation or be called _id
  _id: z.string().optional(), // For Mongoose compatibility
  name: z.string().min(1, "Name is required"),
  slug: z.string().optional(), // Generated by backend
  description: z.string().optional(),
  price: z.number().positive("Price must be positive"),
  images: z.array(z.string().url()).min(1, "At least one image is required"),
  imageUrl: z.string().url().optional(), // Backwards compatibility for now
  variants: z.array(ProductVariantSchema).default([]),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});

export type ProductVariant = z.infer<typeof ProductVariantSchema>;
export type Product = z.infer<typeof ProductSchema>;

export const CreateProductSchema = ProductSchema.omit({ id: true, _id: true, slug: true, createdAt: true, updatedAt: true });
export type CreateProductDTO = z.infer<typeof CreateProductSchema>;
